
redis:
  #hostname of the redis server
  hostname: localhost
  #database id
  database: 1
  #time to live for cache objects 
  ttl: 3600

domains:
  "gmail.com":
    disable_cache: false
    subnets:
      - range: 93.115.18.97-93.115.18.105 
        max_messages: 10
        max_interval: 1
        fallback_helo_host: mailman 
  
  "yahoo.com":
    disable_cache: false
    subnets:
      - range: 93.115.18.106-93.115.18.111
        max_messages: 10
        max_interval: 1
        fallback_helo_host: mailman 
  
  default:
    disable_cache: true
    subnets:
      - range: 93.115.18.111-93.115.18.126
        max_messages: 10
        max_interval: 1
        fallback_helo_host: mailman 


