redis:
  #hostname of the redis server
  hostname: localhost
  #database id
  database: 1
  #time to live for cache objects 
  ttl: 3600

domains:
#
# <recieving domain>: # the name of the domain is receiving the emails or "default" as a fallback rule
#                     # if receiving domain doesn't match a more specific rule.
#   disable_cache: false # true disables the caching mechanism (caching = send mails to a remote address from the same ip address when cache mechanism is on)
#   subnets: #list of subnets
#     - range: <start-ip>-<end-ip> #the range can spawn accross multiple /24
#       max_messages: <integer> #the maximum number of messages that 
#                               #should be sent using an ip address from this subnet
#                               #after this number is reached the ip is incremented
#       max_interval: <integer> #maximum amount of time that this subnet yields an ip addresse
#                               #after this amount of time the ip is incremented
#       fallback_helo_host: <hostname>  #a hostname that should be used in the case of a reverse
#                                       #dns lookup failure for an ip from this subnet
#
#
  "gmail.com":
    disable_cache: false
    subnets:
      - range: 93.115.19.3-93.115.19.190
        max_messages: 2
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman 
  
  "google.com":
    disable_cache: false
    subnets:
      - range: 93.115.19.3-93.115.19.190
        max_messages: 2
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman

  "googlemail.com":
    disable_cache: false
    subnets:
      - range: 93.115.19.3-93.115.19.190
        max_messages: 2
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman

  "yahoo.com":
    disable_cache: false
    subnets:
      - range: 93.115.19.3-93.115.19.254
        max_messages: 2
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman 

  "yahoo.co.uk":
    disable_cache: false
    subnets:
      - range: 93.115.19.3-93.115.19.254
        max_messages: 2
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman
 
  "yahoo.fr":
    disable_cache: false
    subnets:
      - range: 93.115.19.3-93.115.19.254
        max_messages: 2
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman

  "hotmail.com":
    disable_cache: false
    subnets:
      - range: 93.115.19.3-93.115.19.254
        max_messages: 2
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman


  default:
    disable_cache: false
    subnets:
      - range: 93.115.19.1-93.115.19.180
        max_messages: 4
        max_interval: 240
        max_errors: 500
        fallback_helo_host: mailman 


