#!/usr/bin/env python
#
# TODO:
# Reply status code
# Cache - Done
# Persistent State - Done
#


from twisted.internet import protocol, reactor
import sys
from qmail_outip import IpManagerFactory,IpAllocator,log
import yaml
from redis import Redis


try:
  config = yaml.load(file(sys.argv[1]))
except IndexError:
  print "%s <config file>"%(sys.argv[0])
  sys.exit(1)

allocator = IpAllocator(config)
port = int(config.get("port") or 9000)

reactor.listenTCP(port, IpManagerFactory(allocator))
log.info("Listening on port %d",port)
reactor.run()



